version: "2.1"
services:
  mycollect:
    image: mathrb/mycollect:latest
    container_name: mycollect
    volumes:
      - ${PWD}/storage:/storage
      - ${PWD}/config.yaml:/app/config.yaml
      - ${PWD}/logs:/app/logs
    restart: unless-stopped