collectors:
  - name: twitter
    type: mycollect.collectors.twitter_collector.TwitterCollector
    args:
      output_file: new_twitter_collect.jsonl
      consumer_key: twitter consumer_key
      consumer_secret: twitter consumer_secret
      access_token: twitter access_token
      access_secret: twitter access_secret
      languages:
        - en
      low_priority_url:
        - t.co
        - twitter.com
      track:
        - python
        - nodejs
        - kubernetes aws
        - batman and robin

data_manager:
  type: mycollect.data_manager.file_data_manager
  args:
    folder: storage

processing:
  execution_time: "18:00"

processors:
  - name: file
    type: mycollect.processors.file_processor.FileProcessor
    args:
      input_file: new_twitter_collect.jsonl

outputs:
  - name: email
    type: mycollect.output.email_output.EmailOutput
    args:
      aws_access_key: aws aws_access_key
      aws_secret_key: aws aws_secret_key
      aws_region: us-west-2
      sender: Collect <mathrb@gmail.com>
      recipients:
        - mathrb@gmail.com
      limit_per_category: 3
      template: | 
        <html>
        <head></head>
        <body>
            <h1>News Reporting</h1>{% for category, items in results.items() %}
                <h2>{{ category }}</h2>{% for item in items %}
                    <p>({{item["count"]}}) {{item["text"]}} <br> <a href='{{item["url"]}}' >{{item["url"]}}</a></p>{% endfor %}
                <br>{% endfor %}
        </body>
        </html>


logging:  
  version: 1
  disable_existing_loggers: true
  handlers:
      console:
        level: DEBUG
        class : logging.StreamHandler
        formatter: plain_colored
        stream  : ext://sys.stdout
      file:        
        level: INFO
        class : logging.handlers.TimedRotatingFileHandler
        formatter: json
        filename: logs/logconfig.log
        when: D
        interval: 1
  formatters:
      json: 
        class: pythonjsonlogger.jsonlogger.JsonFormatter
      plain_colored:
        (): mycollect.logger.plain_colored_formatter
  loggers:
    mycollect:
      handlers: 
        - file
        - console
      level: DEBUG