# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and Test mycollect 

on:
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches: 
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Lint with pylint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run pylint mycollect
    - name: Test with pytest
      run: |
        pipenv run pytest . --cov=mycollect --cov-fail-under 90
